# Generated by Django 5.1.2 on 2026-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='difficulty',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='weekly_goal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
