# Generated by Django 5.1.2 on 2026-03-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_monitoring_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
