# Generated by Django 5.1.2 on 2026-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
