# Generated by Django 5.1.2 on 2026-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motivation_quote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
