# Generated by Django 5.1.2 on 2026-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_motivation_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
