# Generated by Django 5.1.2 on 2026-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_icons/'),
        ),
    ]
