# Generated by Django 5.1.2 on 2026-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_sociallink_icon_url_sociallink_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('all', 'All'), ('admin', 'Admin'), ('curator', 'Curator'), ('student', 'Student'), ('none', 'None')], default='all', max_length=10),
        ),
    ]
