# Generated by Django 5.1.2 on 2026-03-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_notification_target_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='motivation_quote',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
