# Generated by Django 5.1.2 on 2026-03-14 — manually adjusted
#
# PROBLEM: Django's AlterField with db_index=True tries CREATE INDEX, but the
# DB already has most of these indexes from previous implicit creation.
# SOLUTION: Replace AlterField + implicit index creation with:
#   1. RunSQL(CREATE INDEX IF NOT EXISTS) to avoid DuplicateTable errors
#   2. Keep AlterField state_operations so Django's migration state is accurate
#   3. Only AddIndex for composite indexes that are genuinely new

from django.db import migrations, models


def add_index_if_not_exists(index_name, table, columns):
    """Helper to generate RunSQL operations that are idempotent."""
    col_str = ', '.join(columns)
    return migrations.RunSQL(
        sql=f"CREATE INDEX IF NOT EXISTS {index_name} ON {table} ({col_str});",
        reverse_sql=f"DROP INDEX IF EXISTS {index_name};",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_motivation_quote'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # ── ChatMessage.timestamp (already indexed as api_chatmessage_timestamp_868658a4) ──
        add_index_if_not_exists('api_chatmessage_timestamp_868658a4', 'api_chatmessage', ['timestamp']),

        # ── Monitoring.status — new index ─────────────────────────────────────
        add_index_if_not_exists('api_monitoring_status_idx', 'api_monitoring', ['status']),

        # ── Monitoring.week_number (already indexed as api_monitoring_week_number_8c2a4314) ──
        add_index_if_not_exists('api_monitoring_week_number_8c2a4314', 'api_monitoring', ['week_number']),

        # ── Notification.target_role (already as api_notification_target_role_e55f20b8) ──
        add_index_if_not_exists('api_notification_target_role_e55f20b8', 'api_notification', ['target_role']),

        # ── Notification.timestamp (already as api_notification_timestamp_17e1b10d) ──
        add_index_if_not_exists('api_notification_timestamp_17e1b10d', 'api_notification', ['timestamp']),

        # ── Season.is_active (new) ─────────────────────────────────────────────
        add_index_if_not_exists('api_season_is_active_idx', 'api_season', ['is_active']),

        # ── User.is_approved (already as api_user_is_approved_fbe455c3) ─────────
        add_index_if_not_exists('api_user_is_approved_fbe455c3', 'api_user', ['is_approved']),

        # ── User.role (already as api_user_role_aa482fe1) ────────────────────
        add_index_if_not_exists('api_user_role_aa482fe1', 'api_user', ['role']),

        # ── User.status (already as api_user_status_33b427dc) ────────────────
        add_index_if_not_exists('api_user_status_33b427dc', 'api_user', ['status']),

        # ── WeeklyHighlight.week_number (new) ─────────────────────────────────
        add_index_if_not_exists('api_weeklyhighlight_week_number_idx', 'api_weeklyhighlight', ['week_number']),

        # ── Update Django's internal state for field changes ──────────────────
        # These AlterField calls do NOT create DB indexes (we already handled
        # them above with RunSQL IF NOT EXISTS). They only update Django's
        # internal migration state so it knows the fields have db_index=True.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='chatmessage',
                    name='timestamp',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='monitoring',
                    name='status',
                    field=models.CharField(
                        choices=[
                            ('Bajarilmoqda', 'Bajarilmoqda'),
                            ('Hal qilindi', 'Hal qilindi'),
                            ('Kutilmoqda', 'Kutilmoqda'),
                            ('Bajarmadi', 'Bajarmadi'),
                        ],
                        db_index=True, default='Kutilmoqda', max_length=20,
                    ),
                ),
                migrations.AlterField(
                    model_name='monitoring',
                    name='week_number',
                    field=models.IntegerField(db_index=True),
                ),
                migrations.AlterField(
                    model_name='notification',
                    name='target_role',
                    field=models.CharField(
                        choices=[
                            ('all', 'All'), ('admin', 'Admin'),
                            ('curator', 'Curator'), ('student', 'Student'), ('none', 'None'),
                        ],
                        db_index=True, default='all', max_length=10,
                    ),
                ),
                migrations.AlterField(
                    model_name='notification',
                    name='timestamp',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                migrations.AlterField(
                    model_name='season',
                    name='is_active',
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='is_approved',
                    field=models.BooleanField(db_index=True, default=False),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='role',
                    field=models.CharField(
                        choices=[('admin', 'Admin'), ('curator', 'Curator'), ('student', 'Student')],
                        db_index=True, default='student', max_length=10,
                    ),
                ),
                migrations.AlterField(
                    model_name='user',
                    name='status',
                    field=models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')],
                        db_index=True, default='pending', max_length=10,
                    ),
                ),
                migrations.AlterField(
                    model_name='weeklyhighlight',
                    name='week_number',
                    field=models.IntegerField(db_index=True),
                ),
            ],
            database_operations=[],  # DB work already done above with RunSQL IF NOT EXISTS
        ),

        # ── NEW composite indexes (these are truly new — not in existing DB) ──
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'timestamp'], name='chat_user_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoring',
            index=models.Index(fields=['season', 'curator'], name='monitoring_season_curator_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoring',
            index=models.Index(fields=['season', 'week_number'], name='monitoring_season_week_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoring',
            index=models.Index(fields=['student'], name='monitoring_student_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status', 'is_approved'], name='user_role_status_approved_idx'),
        ),
    ]
