# Generated by Django 5.1.2 on 2026-03-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_indexes_and_fix_userdevice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='monitoring',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='platformsetting',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='weeklyhighlight',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_user_timestamp_idx',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='season',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weeklyhighlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-03-14 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyhighlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'created_at'], name='chat_user_created_idx'),
        ),
    ]
