# Generated by Django 6.0.3 on 2026-03-16 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chatmessage_options_alter_monitoring_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='startup_curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startup_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
