# Generated by Django 6.0.3 on 2026-03-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_startup_curator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_curator',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
