# Generated by Django 6.0.3 on 2026-03-12 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Qurilma nomi (User-Agent)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzili')),
                ('refresh_token', models.TextField(verbose_name='Refresh token (hashed)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi qurilmasi',
                'verbose_name_plural': 'Foydalanuvchi qurilmalari',
                'ordering': ['-last_active'],
            },
        ),
    ]
