# Generated by Django 5.1.2 on 2026-03-14 — manually adjusted
#
# The UserDevice.refresh_token field was originally a TextField.
# We're changing it to CharField(max_length=64, db_index=True).
# The DB already had an implicit index on refresh_token (from the TextField),
# so we use SeparateDatabaseAndState + RunSQL IF NOT EXISTS to handle this.

from django.conf import settings
from django.db import migrations, models


def alter_refresh_token_type(apps, schema_editor):
    """
    Changes refresh_token from TEXT to VARCHAR(64) only on PostgreSQL.
    SQLite doesn't support ALTER COLUMN TYPE and uses manifest typing anyway.
    """
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE authentication_userdevice ALTER COLUMN refresh_token TYPE VARCHAR(64);")


def reverse_alter_refresh_token_type(apps, schema_editor):
    """Reverts VARCHAR(64) back to TEXT on PostgreSQL."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE authentication_userdevice ALTER COLUMN refresh_token TYPE TEXT;")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── refresh_token: TextField → CharField(max_length=64, db_index=True) ──
        # The DB already has an index on this column. We use SeparateDatabaseAndState:
        # - database_operations: ALTER COLUMN type (PG only) + IF NOT EXISTS index creation
        # - state_operations: AlterField to update Django's state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Change the column type only on supported databases
                migrations.RunPython(
                    alter_refresh_token_type,
                    reverse_alter_refresh_token_type,
                ),
                # Ensure the index exists (IF NOT EXISTS is idempotent)
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS authentication_userdevice_refresh_token_08725da8 ON authentication_userdevice (refresh_token);",
                    reverse_sql="DROP INDEX IF EXISTS authentication_userdevice_refresh_token_08725da8;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='userdevice',
                    name='refresh_token',
                    field=models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name='Refresh token (hashed)',
                    ),
                ),
            ],
        ),

        # ── New composite index: user + last_active ────────────────────────────
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'last_active'], name='device_user_last_active_idx'),
        ),
    ]
